# Generated by Django 2.0 on 2021-03-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='')),
                ('shortname', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(default='about your country', max_length=250)),
            ],
        ),
    ]
