# Generated by Django 2.0 on 2021-03-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('country', models.CharField(max_length=250)),
                ('age', models.DurationField()),
                ('role', models.CharField(max_length=250)),
                ('hs', models.IntegerField()),
            ],
        ),
    ]
