# Generated by Django 2.0 on 2021-03-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hs',
        ),
    ]
