# Generated by Django 2.0 on 2021-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210323_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hs',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
