# Generated by Django 2.0 on 2021-03-25 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_player_hs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('dob', models.DateField()),
                ('special', models.CharField(choices=[('bm', 'Batsman'), ('bl', 'Bowler'), ('kp', 'Keeper'), ('al', 'Alrounder')], max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.Country')),
            ],
        ),
    ]
